evangelistalab/forte

.gitignore, CMakeLists.txt, __init__.py, cmake/FindGlobalArrays.cmake, tests/pytest/conftest.py, tests/pytest/test_aci.py, tests/pytest/test_ecp.py
* Requires rewriting tests in PsiAPI mode (straightforward but tedious). Files can contain multiple tests. Most appropriate use of file grouping is to quickly test subset (`pytest -v test_aci.py`)
* To work, requires Psi4 to have [these two lines](https://github.com/psi4/psi4/blob/master/psi4/src/export_plugins.cc#L66-L67) _outside_ the `if` statement. Otherwise only first-run forte test will work.
@jturney
=> CheMPS2, GlobalArrays, pytest

src/aci/aci.cc, src/integrals/conventional_integrals.cc, tests/methods/aci-15/input.dat, tests/methods/aci-15/output.ref
Found a few cases where ncmo_ was passed instead of nact_. Should not affect any old results.
=> Fixes minor bug in handling of dimension

src/forte_old_options.cc, src/mrdsrg-spin-integrated/mrdsrg.cc
MRDSRG relaxation convergence was controlled by e_convergence. This PR separates the convergence criteria so that relaxation process can converge at a larger energy difference where the convergence of HF and CASSCF is not affected.
=> Added variable RELAX_E_CONVERGENCE to control relaxation convergence.

src/mrdsrg-spin-integrated/mrdsrg.cc
This PR prints the recomputed reference energy before the DSRG iterations.
It enables estimation of results during computation when a job takes a long time.
=> Print the reference energy immediately after recomputing.

src/cc/cc.cc, src/helpers/blockedtensorfactory.cc, src/helpers/blockedtensorfactory.h, src/mrdsrg-so/mrdsrg_so.cc, src/mrdsrg-so/so-mrdsrg.cc, src/mrdsrg-spin-integrated/master_mrdsrg.cc, src/orbital-helpers/aosubspace.cc, src/orbital-helpers/semi_canonicalize.cc, src/orbital-helpers/semi_canonicalize.h
Fix warnings in semicanonical and aosubspace. A contribution to Issue #96.
Here are the warnings left on my computer:
- fci/fci_vector_hamiltonian.cc, line 41, unused `required_list`
- fci/fci_vector.cc, line 373, compare int with unsigned long
- mrdsrg-spin-integrated/three_dsrg_mrpt2.cc, unused `nproc`. I do not think this should be fixed.
=> fix warnings in semicanonical and aosubspace

CMakeLists.txt, src/mrdsrg-spin-integrated/three_dsrg_mrpt2.cc
Solve the problem of "Could NOT find TargetOpenMP" when using psi4.
=> adapt for psi4 MathOpenMP

src/sci/aci.cc, tests/methods/aci-14/input.dat
This PR fixes a minor inconsistency in the pruning algorithm that could potentially lead to inefficiencies. This is only a potential issue during the computation of the ground state during multiroot computations when only one root is called at a time.
This code is tested in ACI-14, which should now pass consistently due to decreased convergence thresholds
=> Very small fix in ACI

CMakeLists.txt, src/python_api.cc, src/sparse_ci/stl_bitset_determinant.cc, src/sparse_ci/stl_bitset_determinant.h, tests/pytest/fci_solver.ipynb
This PR exposes the Determinant Class.
```python
>>> import forte
>>> forte.Determinant.num_str_bits
64
>>> forte.Determinant.num_det_bits
128
>>> a = forte.Determinant([True,False,True],[False,True,True])
>>> a.get_alfa_bits()
5
>>> a.get_beta_bits()
6
>>> bin(a.get_beta_bits())[:1:-1]
'011'
>>> b = forte.Determinant()
>>> b.get_alfa_bits()
0
```
- This PR currently only works with `UI64Determinants`, because the return type `std::bitset` of `STLBitsetDeterminant::get_alfa_bits()` is not cast successfully to python.
Error message: `TypeError: Unable to convert function return value to a Python type! The signature was
(self: forte.forte.Determinant) -> std::__1::bitset<64ul>`
=> Exposed Determinant class.

src/orbital-helpers/avas.cc
Avoid problems with roundoff errors when AVAS_SIGMA = 1.0. To solve the problem I check that the sum of singular values `sum_i s_i <= avas_sigma + 1.0e-9`. So when `avas_sigma = 1.0` all orbitals are included. To avoid including orbitals with small singular value, I make sure that only orbitals with `s_i > 1.0e-6` are included in the list of actives.
=> Fix AVAS when SIGMA = 1.0

src/integrals/conventional_integrals.cc, src/integrals/conventional_integrals.h, src/integrals/integrals.h
This PR fixes a problem where a psi4 DPD buffer was never properly closed
=> Do not store an IntegralTransform object in the ForteIntegrals class

pymodule.py, tests/methods/tests.yaml, tests/methods/x2c-1/output.ref
Fix the problem introduced in PR #200 due to testing orbital orthonomality, which calls MintsHelper to build SO overlap integrals.
=> Fix Problems of Running Relativistic Computations

src/sci/aci_build_F.cc, src/sci/gasaci_build_F.cc, src/sparse_ci/sigma_vector_sparse_list.cc
Revert back to Jeff's and Meng's approach for building sorting list in ACI and GAS-ACI.
It turns out the original code is way faster than the straightforward `pragma omp parallel for`.
=> ACI and GAS-ACI optimization for building sorting list

src/helpers/helpers.h, src/sci/aci.cc, src/sparse_ci/ci_reference.cc, src/sparse_ci/ci_reference.h, tests/methods/gasaci-1/output.ref, tests/methods/gasaci-4/output.ref, tests/methods/gasci-1/output.ref, tests/methods/gasci-2/output.ref
Make the GAS reference code more compact.
The algorithm for generating GAS determinants is the following:
```
1. for each GAS electron occupation, do
2.     generate alpha/beta strings for each GAS subspace, classified according to irrep
3.     compute the Cartesian product (i.e., itertools.product in Python) of the result of line 2
4.     for each product in line 3, do
5.         build alpha/beta string of size the number of active orbitals, classified according to irrep
6.         end do
7.     combine alpha/beta strings to match the required symmetry
8.     end do
```
=> Shorten GAS code in CI_Reference

CMakeLists.txt, azure-pipelines.yml, src/base_classes/mo_space_info.cc, src/base_classes/mo_space_info.h, src/helpers/symmetry.h, tests/methods/dsrg-mrpt2-13/input.dat, tests/pytest/mospaceinfo/test_mospaceinfo2.py, tools/forte_codecov
Add azure pipeline for CI of forte.
Currently, I compile Psi4, Ambit, and Forte using consistent compilers. All tests pass for gcc-7.5 (see tests of commit a9e4e9c [here](https://github.com/evangelistalab/forte/runs/1841031309)), but testing is slow (not sure if caused from omp linking).
Several strategies to save some time for later testing:
1. conda psi4, conda ambit: ~~not successful, due to problems of Psi4 introduced in PR 2048. Need to wait psi4 conda package get updated.~~ Still not successful after psi4 conda updated because `-std=c++-14` is there possibly due to Psi4 (see [here](https://dev.azure.com/fevange/Forte/_build/results?buildId=90&view=logs&j=d5e0e3a1-017b-5abf-d511-c7b6c880a863&t=0c5c7dab-a85c-5649-60c1-2c9333423668&l=31)). Also, not sure if Pybind11 works cross …
=> Azure Pipeline

forte/fci/fci_vector_h_diag.cc, forte/fci/fci_vector_rdm.cc, forte/integrals/integrals_psi4_interface.cc, forte/mrdsrg-spin-adapted/sadsrg_block_labels.cc, forte/mrdsrg-spin-adapted/sadsrg_comm.cc, forte/mrdsrg-spin-integrated/master_mrdsrg.cc
This PR adds 6 <algorithm> header for 6 source files which leads to an error compiling with g++ on ubuntu.
- Add #include<algorithm> for source code used them.
=> Adding algorithm header for 6 source files

forte/__init__.py, setup.py
This PR adds the ability to compile Forte using a `setup.py` file.
After the user has compiled/installed psi4 and ambit there are two steps:
1. Tell `setup.py` where to find ambit, which can be done either by setting the environmental variable `AMBITDIR` to point to the ambit install directory (not that there is no need to append `share/cmake/ambit` as before)
```tcsh
export AMBITPATH=<ambit install dir>
```
or by modifying the `setup.cfg` file to include
```tcsh
[CMakeBuild]
ambitpath=<ambit install dir>
```
2. Compile forte by calling
```tcsh
fortedir> python setup.py develop 
```
or for Debug mode
```tcsh
fortedir> python setup.py build_ext --debug develop
```
This procedure will register forte within pip and you should be able to see forte listed just by calling
```tcsh
pip list
```
=> Add setup.py file

forte/sparse_ci/sparse_exp.cc
Adds a missing include file in `sparse_exp.cc`.
=> Add missing include

forte/orbital-helpers/ci-no/ci-no.cc, forte/orbital-helpers/ci-no/mrci-no.cc
Added the "#include <algorithm>" line in the ci-no.cc and mrci-no.cc files. The std::sort function that is used in these files is defined in header <algorithm>. This fixes potential problems with compilation, especially with gcc compilers.
=> Added "#include <algorithm>" in a couple of files

setup.py
I just realized there is a setup.py. This PR makes the cmake commands more configurable from setup.cfg. For example,
```
[CMakeBuild]
ambitpath=/Users/york/src/ambit-bin-debug
cmake_build_options=-j8 -v
cmake_config_options=-DCMAKE_C_COMPILER=/usr/local/Cellar/llvm/12.0.0/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/Cellar/llvm/12.0.0/bin/clang++ -DCMAKE_Fortran_COMPILER=/usr/local/Cellar/gcc/10.2.0_4/bin/gfortran
```
=> make setup.py more flexible

forte/pymodule.py
This PR simplifies the orthonormality checker. Because we are constructing one less MintsHelper object, the output file is a bit less cluttered with basisset construction.
=> Simplify the orthonormality checker.

forte/api/sci_api.cc, forte/helpers/blockedtensorfactory.cc, forte/sparse_ci/sparse_operator.cc, forte/sparse_ci/sparse_operator.h, forte/sparse_ci/sq_operator.cc, forte/sparse_ci/sq_operator.h, tests/pytest/sparse_ci/test_sparse_operator.py
This PR adds an adjoint method to the `SQOperator` and `SparseOperator` classes, so that I can use the SparseOperator API to correctness-test truncated VCC.
=> Adjoint for SQOperator and SparseOperator

forte/helpers/combinatorial.h
Add the header for `size_t` in `helpers/combinatorial.h`. Somehow the machine I am using does not know where to find `size_t` in this file
=> add header for size_t in combinatorial.h

azure-pipelines.yml, forte/base_classes/active_space_solver.cc, forte/sci/detci.cc
Fix the problem of failing to compute transition RDMs when doing Ms averaging for active space solver.
=> fix the cannot open wfn problem for TRDM when doing spin averaging

azure-pipelines.yml, forte/casscf/casscf.cc, forte/casscf/mcscf_2step.cc, forte/integrals/integrals_psi4_interface.cc, forte/mrdsrg-spin-adapted/sa_mrdsrg_diis.cc, forte/mrdsrg-spin-integrated/mrdsrg_diis.cc
Updates Forte to work with newer version of Psi4. Some recent Psi PRs broke Forte due to:
* Switching to scoped namespaces for DIIS enums, which is the C++ standard
* Switching `Vector::clone` from returning raw pointers to unique pointers. This exposed a memory leak in Forte, as well as very clumsy code. Both are fixed.
The new code compiles, and if auto-tests pass, this should be good to go.
=> Update Forte to work with development Psi4

azure-pipelines.yml, docs/notebooks/nb_07_soints.ipynb, docs/source/nb_03_wavefunction.rst, docs/source/nb_07_soints.rst, docs/source/tutorials.rst, forte/CMakeLists.txt, forte/api/forte_python_module.cc, forte/api/integrals_api.cc, forte/base_classes/active_space_method.cc, forte/base_classes/rdms.h, forte/helpers/spinorbital_helpers.cc, forte/helpers/spinorbital_helpers.h, forte/integrals/integrals.cc, forte/integrals/integrals.h, forte/proc/scc/scc.py, forte/utils/__init__.py, forte/utils/helpers.py, tests/pytest/determinant/test_dets.py, tests/pytest/helpers/test_spinorbital.py, tests/pytest/sparse_ci/srcc/test_uccsd.py, tutorials/Tutorial_01.01_forte_api.ipynb, tutorials/Tutorial_01.03_forte_sparse.ipynb, tutorials/Tutorial_01.04_forte_cc.ipynb, tutorials/Tutorial_02.02_mo_localization.ipynb, tutorials/Tutorial_03.00_DSRG-PT2.ipynb
This PR adds code to export 1- & 2-electron integrals, Fock matrix, RDMs, and cumulants to the python side as numpy arrays. This code can be used for prototyping new methods.
=> Add code to export spin orbital quantities

forte/mrdsrg-spin-integrated/dsrg_mrpt3.cc, forte/mrdsrg-spin-integrated/dsrg_mrpt3.h, forte/register_forte_options.py, tests/methods/dsrg-mrpt3-9/input.dat, tests/methods/dsrg-mrpt3-9/output.ref
Fix the keyword 'DSRG_MRPT3_BATCHED' bug introduced in PR 153.
=> Pt3 force batch

azure-pipelines.yml, codecov.yml, forte/base_classes/state_info.cc, forte/proc/dsrg.py, tests/methods/avas-6/input.dat, tests/methods/fci-ex-1/input.dat, tests/methods/tests.yaml
Fix compatibility issues with Psi4 1.6
=> Fix compatibility issues with Psi4 1.6

forte/helpers/iterative_solvers.cc
Fixed printing when an exception occurs in the DL solver.
=> Fix printing of variable

forte/mrdsrg-spin-adapted/sadsrg.cc
Patch zero dimension block for `canonicalize_B` in MRDSRG.
=> Patch zero dimension block for canonicalize_B

forte/base_classes/state_info.h, forte/fci/fci_vector.h, forte/genci/genci_string_address.cc, forte/genci/genci_vector.h, forte/genci/string_lists_makers.cc, forte/sparse_ci/ci_spin_adaptation.h, tests/pytest/determinant/test_string.py
Added necessary header libraries. Fixed correct key type when calling `std::map::at`.
Fixed `test_string.py ` test case.
=> Fixed GCC 13.2 compilation errors

forte/sparse_ci/bitwise_operations.hpp
This PR applies a fix to the return value inconsistency in the `ui64_find_lowest_one_bit` method of `bitwise_operations.cc`, and resolves failing test cases in `tests/code/test_uint64.cc`.
=> Fix bitwise_operations.cc to address return value inconsistency

CMakeLists.txt, THIRD-PARTY-LICENSES, conftest.py, forte/CMakeLists.txt, forte/api/forte_python_module.cc, forte/proc/orbital_helpers.py, pytest.ini
=> Buildconda

forte/orbital-helpers/semi_canonicalize.cc
"INACTIVE_XOCC" also contains "ACTIVE" and will print incorrectly
=> Change semi_canonicalize.cc printing

forte/utils/helpers.py
The `SemiCanonical` class constructor now requires two new arguments `mix_inactive` and `mix_active`. If these are not provided, the error (or lack thereof) can sometimes be opaque (see issue #394). This quick PR fixes the only remaining instance in the codebase where these two arguments aren't provided.
=> Pass new arguments for `SemiCanonical` in `prepare_ints_rdms`

docs/source/methods/mcscf.rst, forte/helpers/helpers.cc, forte/helpers/helpers.h, forte/integrals/integrals.cc, forte/integrals/integrals.h, forte/integrals/integrals_psi4_interface.cc, forte/mcscf/mcscf_2step.cc, forte/mcscf/mcscf_orb_grad.cc, forte/mcscf/mcscf_orb_grad.h, forte/mcscf/mcscf_orb_grad_deriv.cc, forte/options.yaml, forte/pymodule.py, tests/manual/mcscf-5/input.dat, tests/methods/aci_scf-1/input.dat, tests/methods/casscf-3/input.dat, tests/methods/casscf-5/input.dat, tests/methods/casscf-6/input.dat, tests/methods/casscf-fcidump-1/input.dat, tests/methods/casscf-gradient-2/input.dat, tests/methods/casscf-gradient-3/input.dat, tests/methods/casscf-opt-3/input.dat, tests/methods/df-casscf-1/input.dat, tests/methods/df-casscf-gradient-1/input.dat, tests/methods/df-casscf-gradient-1/output.ref, tests/methods/df-casscf-gradient-2/input.dat, tests/methods/df-casscf-gradient-2/output.ref, tests/methods/df-dsrg-mrpt2-7-localized-actv/input.dat, tests/methods/tests.yaml
The previous version of analytic DF-MCSCF gradient code dumps 4-index 2-RDM elements via Psi4 `IWL`. This PR implements the genuine analytic DF-MCSCF gradients by saving the 3-index and 2-index 2-RDMs contributions to Psi4 `PSIO`.
There is also an algorithmic change of building the 3-active/1-general 2-electron integrals in DF-MCSCF. Previous implementation computes MO integrals (pu|xy) using JK builder for every xy slice, which turns out to be good for small active spaces. For the larger active space (NA > 20), this `TEIALG::JK` approach does not scale. This PR switches to the `TEIALG::DF` approach that relies on `DFHelper` of Psi4 to obtain (Q|pu) 3-index MO integrals.
Besides, `MCSCF_FREEZE_CORE` (default: `False`) is replaced by `MCSCF_IGNORE_FROZEN_ORBS` (default: `True`) because …
=> Add genuine analytic DF-MCSCF gradients

forte/api/sparse_state_api.cc, forte/sparse_ci/sparse_state.cc, forte/sparse_ci/sparse_state.h, tests/pytest/sparse_ci/test_sparse_state.py
Add ability to calculate <Psi0|S^2|Psi1> where Psi0 and Psi1 are `SparseState` objects. Also normalize (global function) function for `SparseState`.
=> SparseState spin2

forte/api/sparse_hamiltonian_api.cc, forte/sparse_ci/sparse_hamiltonian.cc, forte/sparse_ci/sparse_hamiltonian.h, tests/pytest/sparse_ci/test_sparse_operator2.py
This is a very short PR adding a small convenience function that converts a `SparseHamiltonian` object (initialized by an `ActiveSpaceIntegral`) into a `SparseOperator` object. Thanks @imagoulas for catching this use case!
=> SparseHamiltonian to SparseOperator

forte/utils/helpers.py, tests/pytest/helpers/test_helpers.py, tutorials/Tutorial_01.02_forte_dets.ipynb
Recent changes in APIs broke the `forte.utils.prepare_forte_objects` function and a tutorial. This short PR fixes them.
=> Fix `prepare_forte_objects` and a tutorial

forte/api/sparse_operator_list_api.cc, forte/helpers/math_structures.h, tests/pytest/sparse_ci/test_sparse_operator.py
This PR implements and exports the `+` and `+=` operators for `VectorSpaceList` (upstream to `SparseOperatorList` etc). The behavior on the python side is the expected behavior for the addition of two lists, i.e., concatenation.
=> add and iadd for VectorSpaceList

forte/api/determinant_api.cc, forte/sparse_ci/bitarray.hpp, forte/sparse_ci/determinant.hpp, tests/pytest/determinant/test_dets.py
This PR adds a class function `excitation_connection` to `DeterminantImpl`. This function takes in another arbitrary determinant (e.g. different number of electrons) and describes the excitation connection from this determinant to the input determinant in the form of a vector of vectors: `[[alfa holes], [alfa particles], [beta holes], [beta particles]]`.
For example, `det("20").excitation_connection(det("0+")) == [[0],[1],[0],[]]`.
=> Compute the excitation connection between two determinants

forte/api/determinant_api.cc, forte/helpers/determinant_helpers.cc, forte/helpers/determinant_helpers.h, forte/sparse_ci/determinant.hpp, tests/pytest/determinant/test_hilbert_space.py
This PR is a small modification on the `make_hilbert_space` function that allows one to truncate the total excitation rank relative to the aufbau determinant.
=> Generate truncated hilbert spaces

forte/helpers/math_structures.h, tests/pytest/sparse_ci/test_sparse_state.py, tests/pytest/srcc/test_ccsd.py, tests/pytest/srcc/test_ccsd_3.py, tests/pytest/srcc/test_ccsdtq.py, tests/pytest/srcc/test_ccsdtq_2.py, tests/pytest/srcc/test_dccsd.py, tests/pytest/srcc/test_dccsd_2.py, tests/pytest/srcc/test_dccsdtq.py, tests/pytest/srcc/test_duccsd.py, tests/pytest/srcc/test_duccsdt.py, tests/pytest/srcc/test_duccsdtq.py, tests/pytest/srcc/test_uccsd.py, tests/pytest/srcc/test_uccsd_2.py, tests/pytest/srcc/test_uccsdt.py
This PR restores the expected behavior of `forte.overlap(a,b) == <a|b>`, where before the ket was whichever one of `a` or `b` that's the shorter vector. This should only impact results where the vectors have complex coefficients. A test has been added to that effect.
=> Make `forte.overlap` respect argument order
