- .travis.yml
- tests/methods/casscf-3/input.dat
- tests/methods/cd-dsrg-mrpt2-4/input.dat
Fixes recent issues with Travis CI.
> Fix Travis

- src/semi_canonicalize.cc
> temporary fix the semicanonical problem when doing DF

- CMakeLists.txt
- pymodule.py
- src/aci/aci.cc
- src/ao_helper.cc
- src/integrals/df_integrals.cc
- src/integrals/diskdf_integrals.cc
- src/integrals/integrals.h
- src/main.cc
- src/sparse_ci/sparse_ci_solver.cc
Small changes in Forte required with the newest Psi.
Mostly, these changes are in response to name changes in the DFHelper class.
> Version compiles with new Psi1.2

- tests/performance/aci-1/input.dat
- tests/performance/aci-1/output.ref
- tests/performance/diskdf-dsrg-mrpt2-1/input.dat
- tests/performance/diskdf-dsrg-mrpt2-1/output.ref
- tests/performance/fci-1/input.dat
- tests/performance/fci-1/output.ref
- tests/performance/mrdsrg-ldsrg2-df-seq-nivo-1/input.dat
- tests/performance/mrdsrg-ldsrg2-df-seq-nivo-1/output.ref
- tests/performance/pci-1/input.dat
- tests/performance/pci-1/output.ref
- tests/performance/run_forte_timings.py
This PR corrected the performance tests.
> Corrected performance test.

- src/aci/aci.cc
- src/aci/aci.h
Very small pr, but something that needed to be cleaned up.
The goal is to add a function and corresponding option to print an ACI wave function to a file. The function will create a .txt file with the expansion coefficient and corresponding occupation vector printed on each line.
> Add function to print final wave function to a file

- src/aci/aci.cc
- src/helpers.h
> Remove redundant definition of timer

- src/cc/cc.cc
- src/helpers/helpers.cc
- src/helpers/helpers.h
- src/helpers/iterative_solvers.h
- src/helpers/mo_space_info.cc
- src/helpers/mo_space_info.h
- src/pci/ewci.cc
- src/pci/ewci.h
- src/pci/pci.cc
- src/pci/pci.h
- src/pci/pci_hashvec.cc
- src/pci/pci_hashvec.h
- src/pci/pci_simple.cc
- src/pci/pci_simple.h
This PR removes some warnings.
> Solve warnings.

- src/base_classes/active_space_solver.cc
- src/base_classes/active_space_solver.h
- src/base_classes/dynamic_correlation_solver.cc
- src/base_classes/dynamic_correlation_solver.h
- src/base_classes/reference.cc
- src/base_classes/reference.h
- src/fci/fci_integrals.cc
- src/fci/fci_integrals.h
- src/fci/fci_solver.cc
- src/fci/fci_solver.h
- src/fci/fci_vector_rdm.cc
- src/fci/sa_fcisolver.cc
- src/fci/string_oo_list.cc
- src/fci/string_vo_list.cc
- src/fci/string_vvoo_list.cc
Eliminates (almost all) warnings stemming from files in fci/ folder
> Removed warnings in fci/ folder

- src/casscf/casscf.cc
- src/orbital-helpers/ao_helper.cc
- src/orbital-helpers/ao_helper.h
- src/orbital-helpers/aosubspace.cc
- src/orbital-helpers/avas.cc
- src/orbital-helpers/ci-no/ci-no.cc
- src/orbital-helpers/ci-no/mrci-no.cc
- src/orbital-helpers/es-nos.cc
- src/orbital-helpers/es-nos.h
- src/orbital-helpers/iao_builder.cc
- src/orbital-helpers/localize.cc
- src/orbital-helpers/mp2_nos.cc
- src/orbital-helpers/orbitaloptimizer.cc
- src/orbital-helpers/semi_canonicalize.cc
- src/orbital-helpers/unpaired_density.cc
This PR fixes warnings in casscf, finite temperature, orbital-helpers/*
> Fix warnings (casscf and orbital-helper)

- src/mrdsrg-helper/dsrg_source.h
- src/mrdsrg-helper/dsrg_time.cc
- src/mrdsrg-so/mrdsrg_so.cc
- src/mrdsrg-so/so-mrdsrg.cc
- src/mrdsrg-so/so-mrdsrg.h
- src/mrdsrg-spin-adapted/dsrg_mrpt.cc
- src/mrdsrg-spin-adapted/dsrg_mrpt.h
- src/mrdsrg-spin-adapted/dsrg_mrpt_2nd.cc
- src/mrdsrg-spin-adapted/dsrg_mrpt_amp.cc
- src/mrdsrg-spin-adapted/dsrg_mrpt_comm.cc
- src/mrdsrg-spin-integrated/active_dsrgpt2.cc
- src/mrdsrg-spin-integrated/active_dsrgpt2.h
- src/mrdsrg-spin-integrated/dsrg_mrpt2.cc
- src/mrdsrg-spin-integrated/dsrg_mrpt2.h
- src/mrdsrg-spin-integrated/dsrg_mrpt2_ms.cc
- src/mrdsrg-spin-integrated/dsrg_mrpt3.cc
- src/mrdsrg-spin-integrated/dsrg_mrpt3.h
- src/mrdsrg-spin-integrated/dwms_mrpt2.cc
- src/mrdsrg-spin-integrated/master_mrdsrg.cc
- src/mrdsrg-spin-integrated/master_mrdsrg.h
- src/mrdsrg-spin-integrated/mcsrgpt2_mo.cc
- src/mrdsrg-spin-integrated/mrdsrg.cc
- src/mrdsrg-spin-integrated/mrdsrg.h
- src/mrdsrg-spin-integrated/mrdsrg_amplitude.cc
- src/mrdsrg-spin-integrated/mrdsrg_pt.cc
- src/mrdsrg-spin-integrated/mrdsrg_smart_s.cc
- src/mrdsrg-spin-integrated/mrdsrg_srg.cc
- src/mrdsrg-spin-integrated/three_dsrg_mrpt2.cc
Contributions to Issue #96.
Fix warnings in
> fix warnings

- pymodule.py
- tests/methods/df-dsrg-mrpt2-7-localized-actv/input.dat
- tests/methods/dsrg-mrpt2-12-localized-actv/input.dat
- tests/methods/dsrg-mrpt3-6-sa/input.dat
- tests/methods/dsrg-mrpt3-8-sa-C2H4/input.dat
- tests/methods/mr-dsrg-pt2-1/input.dat
- tests/methods/tests.yaml
Fix the SA tests that are not tested by travis.
> Fix SA tests due to recent changes

- src/base_classes/dynamic_correlation_solver.cc
- src/casscf/casscf.cc
- src/finite_temperature/finite_temperature.cc
- src/integrals/integrals.cc
- src/orbital-helpers/avas.cc
- src/orbital-helpers/ci-no/ci-no.cc
- src/orbital-helpers/iao_builder.cc
- src/orbital-helpers/orbitaloptimizer.cc
- src/orbital-helpers/unpaired_density.cc
- src/sci/aci.cc
- src/sparse_ci/sparse_ci_solver.cc
> Make calls to psi4 Matrix compatible with new interface

- .travis.yml
- CMakeLists.txt
- src/main.cc
> Switch to pybind11_add_module

- .travis.yml
Added python tests for Determinant API
> Add more functions to the Determinant class API

- register_forte_options.py
- src/mrdsrg-so/so-mrdsrg.cc
- src/mrdsrg-spin-integrated/dsrg_mrpt3.cc
- src/mrdsrg-spin-integrated/dsrg_mrpt3.h
- tests/methods/aci-20/input.dat
- tests/methods/dsrg-mrpt3-9/input.dat
- tests/methods/tests.yaml
This PR tests more parts of the DSRG-MRPT3 code.
> Test more parts of the code

- src/integrals/active_space_integrals.cc
This PR fixes the overflow problem in the active space integrals print function. Resolves #154.
> Fix print overflow problem

- CMakeLists.txt
- src/mrdsrg-spin-integrated/active_dsrgpt2.cc
- src/mrdsrg-spin-integrated/active_dsrgpt2.h
- src/mrdsrg-spin-integrated/dwms_mrpt2.h
- src/mrdsrg-spin-integrated/mcsrgpt2_mo.cc
- src/mrdsrg-spin-integrated/mrdsrg.h
- src/mrdsrg-spin-integrated/mrdsrg_commutator.cc
- src/mrdsrg-spin-integrated/three_dsrg_mrpt2.cc
- src/mrdsrg-spin-integrated/three_dsrg_mrpt2.h
- src/sci/fci_mo.cc
- src/sci/fci_mo.h
- tests/methods/mrdsrg-ldsrg2-df-4/input.dat
- tests/methods/tests.yaml
Increases code coverage of MRDSG methods
> Improve code coverage II

- .travis.yml
- .travis.yml.compilePsi4
- .travis.yml.conda
> Try to compile psi4 on Travis CI

- pymodule.py
- src/base_classes/mo_space_info.h
- src/base_classes/rdms.h
- src/python_api.cc
- tests/pytest/mospaceinfo/test_mospaceinfo.py
- tests/pytest/sparse_ci/test_sparse_ci.py
- tools/forte_codecov
- utils/__init__.py
- utils/psi4_scf.py
> Expose the MOSpaceInfo class to python

- src/integrals/active_space_integrals.cc
- src/sci/aci.cc
- tests/methods/aci-12/input.dat
- tests/methods/tests.yaml
> Fix bug in slater_rules() and fix aci-12

- src/api/forte_python_module.cc
- src/api/state_info_api.cc
- src/base_classes/state_info.cc
- src/base_classes/state_info.h
- tutorials/ForteCon2020/gas/.ipynb_checkpoints/gas_tutorial-checkpoint.ipynb
- tutorials/ForteCon2020/gas/gas_tutorial.ipynb
This pr adds a tutorial for the GAS functionality in forte. It also fixed issue #212.
> ForteCon20 GAS tutorial and fix to #212

- src/base_classes/active_space_solver.cc
- src/sci/detci.cc
Fix a bug when doing SA_SUB with spin-adapted DSRG.
> fix sa_sub when doing spin-adapted

- src/mrdsrg-spin-integrated/dwms_mrpt2.cc
This PR removes an unused line of code that was triggering a compiler warning.
> Resolve compiler warning

- forte/orbital-helpers/iao_builder.cc
Add include algorithm for iao_builder.cc
> add include algorithm for iao_builder.cc

- forte/mrdsrg-spin-adapted/dsrg_mrpt_amp.cc
Added missing "#include <algorithm>" in dsrg_mrpt_amp.cc.
> Added missing 'include <algorithm>'

- forte/sparse_ci/determinant_hashvector.cc
- forte/sparse_ci/sorted_string_list.cc
> add missing include

- forte/sci/asci.cc
- forte/sparse_ci/sparse_exp.cc
> add algorithm in asci and sparse_exp

- forte/mrdsrg-spin-integrated/master_mrdsrg.cc
- setup.py
Spin-integrated DSRG code does not fill in the beta 1RDM correctly. This does not affect any of our published results because we always use low-spin configuration.
> Bug fix for high-spin DSRG

- forte/sci/detci.cc
This PR improves an error message in DETCI that is triggered if no determinants are found.
> Fix error message in DETCI

- azure-pipelines.yml
- forte/__init__.py
- forte/casscf/casscf_orb_grad.cc
- forte/casscf/casscf_orb_grad.h
- forte/casscf/mcscf_2step.cc
- forte/core.py
- forte/helpers/helpers.cc
- forte/integrals/df_integrals.cc
- forte/integrals/diskdf_integrals.cc
- forte/integrals/integrals.h
- forte/integrals/integrals_psi4_interface.cc
- forte/model.py
- forte/pymodule.py
- forte/register_forte_options.py
- forte/utils/helpers.py
- tests/methods/avas-6/input.dat
- tests/methods/avas-6/output.ref
- tests/methods/df-casscf-1/input.dat
- tests/methods/df-casscf-1/output.ref
This PR tries to fix two problems, which are illustrated using the following example:
```
memory 2 gb
import forte
molecule c2{
C        0.000000    2.434170    0.708595
C        0.000000    1.245017    1.402814
C        0.000000    0.000000    0.717010
C        0.000000   -0.000000   -0.717010
C        0.000000    1.245017   -1.402814
C        0.000000    2.434170   -0.708595
H        0.000000   -1.242385    2.490478
H        0.000000    3.378920    1.245642
H        0.000000    1.242385    2.490478
C       -0.000000   -1.245017    1.402814
C       -0.000000   -1.245017   -1.402814
H        0.000000    1.242385   -2.490478
H        0.000000    3.378920   -1.245642
C       -0.000000   -2.434170   -0.708595
C       -0.000000   -2.434170    0.708595
H        0.000000   -1.242385   -2.490478 …
```
> Fix mcscf final orbitals

- forte/api/options_api.cc
- forte/casscf/casscf_orb_grad_deriv.cc
- forte/casscf/cpscf.cc
- forte/casscf/mcscf_2step.cc
- forte/helpers/lbfgs/lbfgs.cc
- forte/helpers/lbfgs/lbfgs.h
- forte/integrals/integrals_psi4_interface.cc
- forte/mrdsrg-spin-integrated/dwms_mrpt2.cc
- forte/orbital-helpers/ao_helper.cc
- forte/orbital-helpers/ci-no/ci-no.cc
- forte/orbital-helpers/ci-no/mrci-no.cc
- forte/orbital-helpers/orbital_embedding.cc
- forte/orbital-helpers/pao_builder.cc
- forte/orbital-helpers/unpaired_density.cc
- forte/pci/pci.cc
- forte/post_process/spin_corr.cc
- forte/sci/aci.cc
- forte/sci/aci_build_F.cc
- forte/sci/asci.cc
Make Forte compilable again after #2628 vector refactor. Also remove unneeded pointers, adding auto, fixing typos...
> Psi-Forte Compatabilities

- azure-pipelines.yml
- tests/methods/mrdsrg-spin-adapted-pt2-1/input.dat
- tests/methods/mrdsrg-spin-adapted-pt2-2/input.dat
Fix azure compilation problems
> Fix azure (Jan. 2023)

- forte/api/sci_api.cc
- forte/base_classes/mo_space_info.cc
- forte/fci/fci_solver.cc
- forte/fci/fci_solver_initial_guess.cc
- forte/fci/fci_vector.cc
- forte/fci/fci_vector.h
- forte/fci/fci_vector_h_diag.cc
- forte/fci/fci_vector_hamiltonian.cc
- forte/fci/fci_vector_rdm.cc
- forte/fci/string_address.cc
- forte/fci/string_address.h
- forte/fci/string_hole_list.cc
- forte/fci/string_lists.cc
- forte/fci/string_lists.h
- forte/fci/string_oo_list.cc
- forte/fci/string_vo_list.cc
- forte/fci/string_vvoo_list.cc
- tests/methods/fci-1/output.ref
This PR implements some changes in the string addressing in the FCI code.
> Updates to the CI codes

- CMakeLists.txt
- forte/CMakeLists.txt
- forte/sparse_ci/bitarray.hpp
- forte/sparse_ci/bitwise_operations.hpp
First PR with c++20 code. Here we improve the determinant class.
> Use C++20 features in the `Determinant` class

- forte/CMakeLists.txt
- forte/api/dl_solver_api.cc
- forte/api/forte_python_module.cc
- forte/api/sci_api.cc
- forte/helpers/davidson_liu_solver.cc
- forte/helpers/davidson_liu_solver.h
- forte/orbital-helpers/ci-no/ci-no.h
- forte/orbital-helpers/ci-no/mrci-no.h
- tests/pytest/dl_solver/test_dl.py
- tests/pytest/dl_solver/test_dl_errors.py
This PR implements a new Davidson-Liu solver. This design improves on the previous version (still used in this PR) in many ways:
- It uses a functional approach, where the user passes a function (via a lambda) that implements the sigma vector build. In this way, the DL algorithm implementation is straightforward and less convoluted than the one currently used.
- A lot of the code is the same, but written using DGEMM and DDOT calls to improve readability and performance.
- The new DL solver is exposed to python and tested extensively on many instances of diagonalization, errors, and correct input.
- The error handling is significantly improved.
- The code improves significantly in the handling of edge cases, and when asking for many roots.
- New features like automatic random guesses …
> New Davidson-Liu solver

- forte/register_forte_options.yaml
> yaml file initial commit

- forte/proc/external_active_space_solver.py
- forte/pymodule.py
> fix external solver after module change

- docs/source/conf.py
- forte/CMakeLists.txt
- setup.py
> Update version of Forte to 0.3.0

- forte/modules/__init__.py
- forte/pymodule.py
- tests/methods/pyscf_interface/input.dat
Fix for the pyscf import error
> Fix for the pyscf import error

- forte/modules/general_cc.py
- forte/sparse_ci/sparse_state_functions.cc
- tests/performance/sparse/sparse_operator_timing.py
- tests/pytest/sparse_ci/test_sparse_operator.py
This PR implements a new, faster algorithm to apply an operator to a sparse state. Other changes focus on replacing the `size()` method with the `len()` function.
Improvements to consistency:
* [`forte/modules/general_cc.py`](diffhunk://#diff-dddac97918ca0e2862a5d41d9d3a44358be5a2406d28eae98df30a7034d4ee93L138-R138): Replaced the `size()` method with the `len()` function in multiple functions to improve consistency and readability. [[1]](diffhunk://#diff-dddac97918ca0e2862a5d41d9d3a44358be5a2406d28eae98df30a7034d4ee93L138-R138) [[2]](diffhunk://#diff-dddac97918ca0e2862a5d41d9d3a44358be5a2406d28eae98df30a7034d4ee93L206-R206) [[3]](diffhunk://#diff-dddac97918ca0e2862a5d41d9d3a44358be5a2406d28eae98df30a7034d4ee93L445-R453)
Enhancements to operator application:
* …
> Implement new `apply` algorithm and fix test cases

- .gitignore
- forte/CMakeLists.txt
- forte/api/ci_rdms_api.cc
- forte/api/determinant_api.cc
- forte/api/forte_python_module.cc
- forte/api/forte_python_module.h
- forte/api/sparse_operator_api.cc
- forte/api/sparse_operator_list_api.cc
- forte/api/sq_operator_string_api.cc
- forte/ci_rdm/ci_rdms.cc
- forte/ci_rdm/ci_rdms.h
- forte/helpers/determinant_helpers.cc
- forte/helpers/math_structures.h
- forte/pymodule.py
- forte/sparse_ci/determinant.hpp
- forte/sparse_ci/sparse_operator.cc
- forte/sparse_ci/sparse_operator.h
- forte/sparse_ci/sq_operator_string.cc
- forte/sparse_ci/sq_operator_string.h
- tests/pytest/sparse_ci/test_sparse_operator.py
- tutorials/Tutorial_01.03_forte_sparse.ipynb
The most notable changes include exposing `CI_RDMS` to Python, enhancements to the `SparseOperator` and `SparseOperatorList` classes, and updates to various APIs.
* Updated `forte/api/forte_python_module.cc` and `forte/api/forte_python_module.h` to export the `CI_RDMS` module. (`forte/api/forte_python_module.cc`, `forte/api/forte_python_module.h`) [[1]](diffhunk://#diff-d2dd1970265492538ec79e9e030c0159547fa055243ac499bcea36550ab9c430R212) [[2]](diffhunk://#diff-58efbb68633fce1c9dd7434e961f632abe4bc749c822594fbb9572e8fb24b695R61)
* Modified the `Determinant` class to include a new method `count_pairs` for counting set pairs of bits. (`forte/api/determinant_api.cc`)
* Enhanced the `SparseOperator` class by adding new methods for arithmetic operations, term addition/removal, and element …
> Expose CI RDMs

- forte/modules/general_cc.py
This PR fixes the DIIS implementation in the general CC / SRCC code. The old implementation saved all iterations instead of the most recent n iterations, and convergence was typically not improved much compared to without DIIS.
> Fix general CC DIIS
